import type { SomeCompanionConfigField } from '@companion-module/base'

export type ModuleConfig = {
	host: string
	port: number
}

export type ModuleSecrets = {
	token: string
}

export function GetConfigFields(): SomeCompanionConfigField[] {
	return [
		{
			type: 'secret-text',
			id: 'host',
			label: 'Controller IP / hostname',
			width: 6,
			default: '127.0.0.1',
			tooltip: 'Graphics PC address shown under Settings → Bitfocus Companion API',
		},
		{
			type: 'number',
			id: 'port',
			label: 'API port',
			width: 3,
			min: 1024,
			max: 65535,
			default: 3176,
		},
		{
			type: 'textinput',
			id: 'token',
			label: 'Private API key',
			width: 9,
			default: '',
			minLength: 16,
			tooltip: 'Private key generated by Broadcast Control. Keep this key secret.',
		},
	]
}

export function isValidConfig(config: ModuleConfig, secrets: ModuleSecrets): boolean {
	return Boolean(
		config.host?.trim() && Number(config.port) >= 1024 && Number(config.port) <= 65535 && secrets.token?.trim(),
	)
}
